spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:blog_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres_pass}

jwt:
  access-token:
    secret: ${ACCESS_TOKEN_SECRET:test_access_secret}
    ttl: ${ACCESS_TOKEN_TTL:86400}
    issuer: ${ACCESS_TOKEN_ISSUER:test_token_issuer}
